### ISSUE TITLE
"display_half_sitting.launch" makes the robot stand straight

### ISSUE THREAD

**Issue by Remy-Rahem-UdeS** [jrl-umi3218/nao_description#3]
Launching "launch/display_half_sitting.launch" in ros makes the robot stand straight instead of being half-sitted.
The values of the legs joints should be different than 0.

**Comment by arntanguy** [comment]
Actually this file does not serve much purpose anymore, as there are now tools in `mc_rtc` that can display the robot model along with the extra information from the `nao_description` package (`rsdf` surfaces, `convex` hulls, etc) with the robot in the halfsitting posture defined in the robot module `mc_nao`. See [mc_surfaces_visualization](https://jrl-umi3218.github.io/mc_rtc/tutorials/tools/mc_surfaces_visualization.html) and [mc_convex_visualization](https://jrl-umi3218.github.io/mc_rtc/tutorials/tools/mc_convex_visualization.html).

For users wishing to see the robot independently of  and we already have the `display.launch` to display the robot independently of `mc_rtc`. Thus I suggest we go ahead and remove that file to avoid duplication.

**Comment by arntanguy** [comment]
Removed in 7641324595216b434bc9615e7cbe6eaae54fac84
